# Generated by Django 4.0.6 on 2022-07-23 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friend',
            field=models.ManyToManyField(related_name='user_friends', through='user_controller.Friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
