# Generated by Django 4.0.6 on 2022-07-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0002_alter_userprofile_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
