# Generated by Django 4.0.6 on 2022-07-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0007_alter_friends_profile_alter_friends_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
